services:
  mtde:
    image: ghcr.io/mlo-tek/missing-trailer-downloader-for-emby:latest
    container_name: MTDE
    ports:
      - "2121:2121"
    volumes:
      - ./config:/config
      - /path/to/media:/media
      # - ./cookies:/cookies:ro
    environment:
      - TZ=Europe/Berlin
      - PUID=99
      - PGID=100
    restart: unless-stopped
